name: reelhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.2.0
  bloc_test: ^10.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  go_router: ^17.1.0
  hydrated_bloc: ^10.1.1
  tmdb_api: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
