name: reelhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.2.0
  bloc_test: ^10.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  go_router: ^17.1.0
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  skeletonizer: ^2.1.2
  talker_bloc_logger: ^5.1.13
  tmdb_api: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
